### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by zeinalii** [data301-2020-winter1/course-project-solo_310#1]
## High priority (must-fix)

- [x] Add a section called analysis, and explain why exactly you chose that specific method of analysis to answer your questions. Why do you think that method of visualization would help you to answer the questions.

- [x] Just graphs alone do not answer your questions. You need to explain how those visualizations answer your questions.

- [x] Add a section called conclusion and summarize your findings and analysis method.

**Comment by amaiya09** [comment]
Thank you for your feedback. I have tried to address it to the best of my abilities by making the required changes.
